words = [
    "adpoint",
    "agentic",
    "asdf",
    "axios",
    "bullmq",
    "chakra",
    "clickthru",
    "combinators",
    "cron",
    "cwd",
    "designiq",
    "dmp",
    "dropzone",
    "dto",
    "eblast",
    "entra",
    "fastly",
    "fns",
    "gke",
    "gpt",
    "graphql",
    "hasura",
    "hono",
    "idp",
    "jsdom",
    "llm",
    "neovim",
    "nuqs",
    "nvim",
    "orpc",
    "osx",
    "phpstan",
    "pino",
    "pnpm",
    "preprod",
    "programmatically",
    "remeda",
    "rmarganti",
    "saml",
    "sharepoint",
    "sso",
    "trpc",
    "ttl",
    "typeorm",
    "unobserve",
    "varchar",
    "vercel",
    "vitest",
    "zod",
    "zustand",
]
